### ISSUE TITLE
Add support for Lucee

### ISSUE THREAD

**Issue by coldfumonkeh** [coldfumonkeh/cfml-ci#18]
Although comparable to Railo 4.2 at present, please can you add a specific Lucee install script to build.xml and to the remote AWS for download and use?

Many thanks

**Comment by marcins** [comment]
I don't do any CF anymore, so don't really have too much motivation to do this - but I'll happily take a pull request, and will upload the required archive to the S3 bucket if i get the source URL.

**Comment by seancorfield** [comment]
Would it perhaps make more sense to use the Maven-compatible dependencies (for both Railo and Lucee and other stuff) that exists here http://cfmlprojects.org/artifacts/org/ instead of using archives from S3?

**Comment by marcins** [comment]
The only reason I put the Railo stuff on S3 originally (as opposed to just the ACF repackaging) was because occasionally the Railo downloads would timeout on TravisCI and fail the build.  If the Lucee download URLs are more reliable then there's no reason they can't be used directly, or any other source.

**Comment by seancorfield** [comment]
Where were you downloading the Railo stuff from? The Maven repo at cfmlprojects.org or the Railo site? I'm suggesting the former if it's fast enough - and getting Lucee from there too (and actually using a Maven-like process to pull it all down).

**Comment by coldfumonkeh** [comment]
Closing this request down as Lucee was include in #19.
Will keep the option of using the cfmlprojects URI close to hand for future updates.
